env:
  global:
    - TERM=dumb
    - secure: Z8T0wcBCsZyY6S+AhIwWtttc5CF7mvRRYLAun3y7E550jK/6EMT7JMPJTuSFmdn89cVZiacPtmjs61Ntpvt/uJR4byx5HlpEnUrL2svl2sMR1QZlw4nLOnuLLu6uCcMSL9VAyuVsg6qTKi75qvXV3D5qYhlpvuY2u82IXjXClUtAnB/hjxbYH6tlz2+FdL+oSMPpuOihdamGE/VfS/CsXmZMooE093+DwM0Yo2BBNfma/BI0nbZMg24zXVeVcOhWBJQJ2AP6LkK34r2tfwrIBhRe2o48fwQpL4UvEnxmaE5sbvXSasVYsXuHaa/uNiwmX7Dv47tmInXDGTR/O2h/kSPF7D8kYauRDfgN+g8PJgO3HauDoWSuOMayj4b73QEYGOzBeXGg/wnWryc0dOLr4qMGeuPQkHtoBvD7mLr4TzccluvhuFvzxSN/xmEx3o2sEBxEqzu4JQt+9eBrC6F2YVWGEQCRdOaiRpVYO/nAvuVOW38F9M12wddfg2ol5tT5C8BqqEQeCgu3s03bm9385x+eFARKYNrr3Mkt2sSHC7+giRsKrzLcMqgd5ogg5bDSu3LzCUERe6WToL5sUHVGrjpXAbYadKEHmZ55xKwXpV2e4uy8ZavgGMz9dVJ1ZUPKESC9LblzryuhSnp+jPTwQngqBRQ23YVFTT1OsQx1Vx0=
language: node_js
node_js: lts/*
addons:
  apt:
    update: true
    packages:
      - libappindicator1
      - fonts-liberation
      - bash
      - curl
      - libxml2-utils
      - google-chrome-stable
      - tree
      - jq
      - sudo
      - python-pip
install: true
before_install:
  - nvm install lts/*
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm i
  - npm run build
cache:
  npm: true
  directories:
    - node_modules
    - ${HOME}/.npm*
    - ${HOME}/.node*
before_deploy:
  - npm i
  - npm run build-gh-pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: ./dist
  target_branch: gh-pages
